name: rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: get app token from rossum
        id: rossum
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.ROSSUM_APP_ID }}
          private_key: ${{ secrets.ROSSUM_PRIVATE_KEY }}

      - name: check out most recent commit
        uses: actions/checkout@v4
        with:
          token: ${{ steps.rossum.outputs.token }}

      - name: rebase
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ steps.rossum.outputs.token }}